services:
  python-ship-trajectory:
    build: .
    image: python-ship-trajectory
    container_name: python-ship-trajectory-container
    tty: true
    privileged: true
    volumes:
      - ".:/code"
    working_dir: /code
    environment:
      PYTHONPATH: /code
